---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: latest

resources:
- name: hipstershoprepo
  type: git
  source:
    uri: ((github-uri))
    branch: ((git-branch))

- name: frontend-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-pass))
    repository: ((docker-hub-repository))/frontend

- name: productcatalogservice-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-pass))
    repository: ((docker-hub-repository))/productcatalogservice

- name: currencyservice-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-pass))
    repository: ((docker-hub-repository))/currencyservice

- name: recommendationservice-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-pass))
    repository: ((docker-hub-repository))/recommendationservice

- name: cartservice-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-pass))
    repository: ((docker-hub-repository))/cartservice

- name: k8s
  type: kubernetes
  source:
    server: https://127.0.0.1:16443
    insecure-skip-tls-verify: true

- name: kubeconfig-file
  type: file
  source:
    filename: config
    content: |
            apiVersion: v1
            clusters:
            - cluster:
                server: https://127.0.0.1:16443
                insecure-skip-tls-verify: true
              name: microk8s-cluster
            contexts:
            - context:
                cluster: microk8s-cluster
                user: admin
              name: microk8s
            current-context: microk8s
            kind: Config
            preferences: {}
            users:
            - name: admin
              user:
                password: ZmRJN29qY2h1N3RnUmllQVQ2eTRGeWNHYjJzKzVuZTBkMlZ6Z3JWTEFHST0K
                username: admin

jobs:
### docker image publish jobs ###
- name: frontend-publish-job
  public: true
  serial: false
  plan:
  - get: hipstershoprepo
    trigger: true
  - put: frontend-docker-image
    params:
      build: hipstershoprepo/src/frontend
      additional_tags: hipstershoprepo/.git/refs/heads/((git-branch))

- name: productcatalogservice-publish-job
  public: true
  serial: false
  plan:
  - get: hipstershoprepo
    trigger: true
  - put: productcatalogservice-docker-image
    params:
      build: hipstershoprepo/src/productcatalogservice
      additional_tags: hipstershoprepo/.git/refs/heads/((git-branch))

- name: currencyservice-publish-job
  public: true
  serial: false
  plan:
  - get: hipstershoprepo
    trigger: true
  - put: currencyservice-docker-image
    params:
      build: hipstershoprepo/src/currencyservice
      additional_tags: hipstershoprepo/.git/refs/heads/((git-branch))

- name: recommendationservice-publish-job
  public: true
  serial: false
  plan:
  - get: hipstershoprepo
    trigger: true
  - put: recommendationservice-docker-image
    params:
      build: hipstershoprepo/src/recommendationservice
      additional_tags: hipstershoprepo/.git/refs/heads/((git-branch))

- name: cartservice-publish-job
  public: true
  serial: false
  plan:
  - get: hipstershoprepo
    trigger: true
  - put: cartservice-docker-image
    params:
      build: hipstershoprepo/src/cartservice
      additional_tags: hipstershoprepo/.git/refs/heads/((git-branch))

## deployment jobs ###
- name: deploy-to-k8s
  plan:
    - get: hipstershoprepo
    - get: kubeconfig-file
    - task: task_replce_image_id
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          inputs:
            - name: hipstershoprepo
          run:
            path: sh
            args:
              - -exc
              - |
                cd hipstershoprepo/
                IMAGE_ID=$(<.git/refs/heads/master)
                echo $IMAGE_ID
                cd kubernetes-specs
                for f in *.yaml; do sed -i "s|IMAGE_ID|$IMAGE_ID|g" "$f"; done
        outputs:
          - name: hipstershoprepo
    - put: k8s
      params:
        kubectl: apply -f hipstershoprepo/kubernetes-specs/ -n hisptershop
        kubeconfig_file: kubeconfig-file/config

#- name: deploy-productcatalogservice-to-k8s
#  plan:
#  - in_parallel:
#      - get: hipstershoprepo
#        passed:
#          - frontend-publish-job
#      - get: kubeconfig-file
#        trigger: true
#      - put: k8s
#        params:
#          kubectl: apply -f hipstershoprepo/kubernetes-specs/productcatalogservice.yaml -n hisptershop
#          kubeconfig_file: kubeconfig-file/config
#
#- name: deploy-currencyservice-to-k8s
#  plan:
#  - in_parallel:
#      - get: hipstershoprepo
#        passed:
#          - frontend-publish-job
#      - get: kubeconfig-file
#        trigger: true
#      - put: k8s
#        params:
#          kubectl: apply -f hipstershoprepo/kubernetes-specs/currencyservice.yaml -n hisptershop
#          kubeconfig_file: kubeconfig-file/config
#
#- name: deploy-recommendationservice-to-k8s
#  plan:
#  - in_parallel:
#      - get: hipstershoprepo
#        passed:
#          - frontend-publish-job
#      - get: kubeconfig-file
#        trigger: true
#      - put: k8s
#        params:
#          kubectl: apply -f hipstershoprepo/kubernetes-specs/recommendationservice.yaml -n hisptershop
#          kubeconfig_file: kubeconfig-file/config
#
#- name: deploy-cartservice-to-k8s
#  plan:
#  - in_parallel:
#      - get: hipstershoprepo
#        passed:
#          - frontend-publish-job
#      - get: kubeconfig-file
#        trigger: true
#      - put: k8s
#        params:
#          kubectl: apply -f hipstershoprepo/kubernetes-specs/cartservice.yaml -n hisptershop
#          kubeconfig_file: kubeconfig-file/config

- name: deploy-redis-to-k8s
  plan:
  - in_parallel:
      - get: hipstershoprepo
        passed:
          - frontend-publish-job
      - get: kubeconfig-file
        trigger: true
      - put: k8s
        params:
          kubectl: apply -f hipstershoprepo/kubernetes-specs/redis.yaml -n hisptershop
          kubeconfig_file: kubeconfig-file/config