---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: latest

- name: file
  type: docker-image
  source:
    repository: quay.io/henry40408/concourse-file-resource

resources:
- name: hipstershoprepo
  type: git
  source:
    uri: ((github-uri))
    branch: ((git-branch))

- name: k8s
  type: kubernetes
  source:
    server: https://192.168.100.8:16443
    insecure-skip-tls-verify: true

- name: kubeconfig-file
  type: file
  source:
    filename: config
    content: |
            apiVersion: v1
            clusters:
            - cluster:
                server: https://192.168.100.8:16443
                insecure-skip-tls-verify: true
              name: microk8s-cluster
            contexts:
            - context:
                cluster: microk8s-cluster
                user: admin
              name: microk8s
            current-context: microk8s
            kind: Config
            preferences: {}
            users:
            - name: admin
              user:
                password: ZmRJN29qY2h1N3RnUmllQVQ2eTRGeWNHYjJzKzVuZTBkMlZ6Z3JWTEFHST0K
                username: admin

jobs:
- name: deploy-to-k8s
  plan:
    - get: hipstershoprepo
    - get: kubeconfig-file
      trigger: true
    - put: k8s
      params:
        kubectl: apply -f hipstershoprepo/kubernetes-specs/redis.yaml -n hisptershop --kubeconfig=kubeconfig-file/config
        kubeconfig_file: kubeconfig-file/config